---
title: "Getting data from the web: API"
date: 2023-11-08T12:25:00-05:00
publishDate: 2019-06-01T12:25:00-05:00
draft: false

aliases: ["/cm015.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
#time_end: 2022-10-31T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Topics: review scraping, define APIs and practice querying APIs."

# Location of event.
location: ""

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
#url_slides: "/slides/getting-data-from-the-web-api-access/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Review main concepts in webscraping
* Define Application Program Interface (API)
* Explain APIs authentication keys and demonstrate secure methods for storing these keys
* Interact with APIs
* Define JSON data structure and how to convert them to data frames

<!--
* Practice tidying messy JSON data objects using `tidyr`
* Demonstrate how to use canned packages in R to access APIs
* Practice gathering data from Twitter API using the `rtweet` package in R
-->

## Before class

Review Monday's class materials and especially:

* install the selector gadget and explore how to use it (see [this slide](https://computing-soc-sci.netlify.app/slides/getting-data-from-the-web-scraping/#43)): it is a handy tool that  makes it easier to select the right tags
* if things in Monday's slides are unclear: come to class with your questions or post them on Ed (I will answer them in-class)
* complete Monday's in-class exercises
* review the readings (there are no new readings for today)

Please notice, several packages are needed for this week's lectures, and they are all installed on R workbench. If you are using R from your laptop (VS. Workbench), I'd suggest following the lectures using Workbench and installing the packages after class.

<!--
* Read [Getting data from the web: API access](/notes/application-program-interface/)
* Read [Getting data from the web: writing API queries](/notes/write-an-api-function/)
-->

## Class materials

TBA

<!--
* Run the code below in your console to download today’s in-class exercises: `usethis::use_course("css-materials/web-api-access")`
-->

<!--
* [Practice getting data from the Twitter API](/notes/twitter-api-practice/)
* [Simplifying lists](/notes/simplify-nested-lists/)
-->
