---
title: "Text analysis"
date: 2023-11-13T12:25:00-05:00
publishDate: 2019-06-03T12:25:00-05:00
draft: true

aliases: ["/cm017.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
#time_end: 2022-11-14T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Introduce methods for text data in R."

# Location of event.
location: ""

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/text-analysis-fundamentals-and-sentiment-analysis/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Identify the basic workflow for conducting text analysis
* Define the tidy text formats (Chapter 1)
* Word frequencies and tf-idf (Chapter 1 and 3)
* Relationship between words (Chapter 4)

Goal of today's and next class: not to become expert in these methods, but to gain an understanding of what can be done with text mining (and further explore some of these topics for your last homework assignment, if you would like)
<!-- 
* Demonstrate how to conduct sentiment analysis using twitter
* Explain how to generate and interpret a wordcloud -->


## Before class

For this and the following lecture we use the book [*Tidy Text Mining with R*](http://tidytextmining.com/):
* Before this class: read Chapter 1, 3, and 4
* Before next class: read chapters 2, 5, and 6


## Class materials

* Run the code below in your console to download today’s in-class materials: `usethis::use_course("css-materials/text-analysis-fundamentals")`

<!--
* [Text analysis: basic workflow](/notes/text-analysis-workflow/)
* [Practicing `tidytext` with song titles](/notes/song-titles-exercise/)
* [Practicing sentiment analysis with Harry Potter](/notes/harry-potter-exercise/)
* Trump twitter account: https://twitter.com/realdonaldtrump
* [Practicing tidytext with Hamilton](/notes/hamilton/)
-->

## Additional resources

* The three case studies included in the book "Text Mining with R" (see assigned readings) provide in-depth examples on how to preform text analysis from A-Z. I recommend Chapter 9  [Case study: analyzing usenet text](https://www.tidytextmining.com/usenet.html)
* For an excellent theoretical explanation of these topics see [Speech and Language Processing](https://web.stanford.edu/~jurafsky/slp3/) by Daniel Jurafsky & James H. Martin, especially Chapter 2, 3, and 4
