---
title: "HW05: Debugging and generating Quarto documents"
date: 2022-10-03T13:30:00-06:00  # Schedule page publish date
publishdate: 2019-04-01

draft: true
type: post

summary: "Resolve code errors and generate reproducible Quarto documents."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Overview

Due by 11:59pm on October 12th.

# Accessing the `hw05` repository

Go [here](https://github.coecis.cornell.edu/cis-fa22) and find your copy of the `hw05` repository. It follows the naming convention `hw05-<USERNAME>`. Clone the repository to your computer.

# Debugging code

The repository contains an R script called `babynames.R`. This script includes code to conduct analysis of baby name popularity in the United States using the [`babynames`](http://hadley.github.io/babynames/) package. Alas its author made some mistakes and the script currently does not work. Fix the errors/warnings in the script to generate the desired output.

# Working with Quarto documents

The homework repository contains a file called `hiv-profile.qmd`.

1. The file has some problems. Fix the problems so you can successfully knit the document in its existing form.
1. Create a [parameterized report](https://quarto.org/docs/computations/parameters.html) that allows you generate `hiv-profile.qmd` for any country in the dataset. Use this parameterized Quarto document to generate a separate report for each country and save them as HTML documents to a folder called `reports`.

{{% callout note %}}

Each file should be named after the country's iso3 code. For example, the report for the United States should be called `USA.html`.

{{% /callout %}}

# Submit the assignment

Your assignment should be submitted as several files:

1. The revised `babynames.R`.
1. The revised `hiv-profile.qmd` and the successfully rendered `hiv-profile.md` with associated output files (e.g. images).
1. An R script that renders all the individual country HIV profiles, as well as rendered HTML files.

Follow instructions on [homework workflow](/faq/homework-guidelines/#homework-workflow).

# Rubric

Needs improvement: The R script has not been successfully fixed. The broken Quarto document still does not knit. You manually generated each country's report.

Satisfactory: Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output). Nothing spectacular, either bad or good.

Excellent: Repository contains a detailed `README.md` explaining how the files in the repo should be executed. Broken Quarto document successfully knits. Used iterative operations to generate each country's HIV profile.


<!--
# Part 2: Using programming in data analysis

The World Bank publishes extensive socioeconomic data on countries/economies around the world. In the `data_world_bank` folder, I have downloaded the World Bank's [complete economic indicators](https://data.worldbank.org/indicator) for each country in their database.

In order to analyze the data, you first need to import it. Each economy's data is stored in a separate `.csv` file.

You should write a function which imports **a single data file**. The function should use one argument (the filepath to the data file). Given this path, the function should read and tidy the economy data, and return the cleaned data frame as the output. Remember the rules for a tidy data frame:

1. Each variable must have its own column.
1. Each observation must have its own row.
1. Each value must have its own cell.

Since the World Bank has hundreds of indicators, your function should pare this down to only the handful of variables you intend to analyze.

Once you have written this function, demonstrate that it works by importing the data files and combining them into a single data frame using an iterative operation.

#### Let's recap the requirements for your function

* Give it a meaningful name
* It should take a single argument - the filepath to the data file. [Chapter 8 of *R for Data Science*](http://r4ds.had.co.nz/workflow-projects.html) explains directory structures and how to access files in a project. **Review this.** You will be marked down if your function requires an absolute file path such as `/Users/soltoffbc/Projects/Computing for Information Science/homework/hw04`
* Do not try and run the iterative operation inside of the function. Technically this can work, but it is far harder to fix errors and write the body of the function if you are performing both tasks simultaneously.
* The output of the function should be a **tidy data frame for a single country, pared down to 2-4 substantive variables you will analyze**.

Once you have the data imported, write a brief report exploring and analyzing at least [two variables in the data](http://data.worldbank.org/indicator). Use a combination of descriptive statistics, tables, and figures, and present your results and analysis in a coherent and interpretable manner. The main point is that your report should not just be code and output from R - you also need to include your own written analysis. Submitting the report as an [Quarto document](http://rmarkdown.rstudio.com/) will make this much easier (and is in fact mandatory).

-->