---
title: "Lecture 5"
date: 2024-10-14T12:25:00-05:00
publishDate: 2019-04-08T12:25:00-05:00
draft: false

#aliases: ["/cm003.html"]

# Talk start and end times.
all_day: false

# Abstract and optional shortened version.
abstract: ""
summary: "<strong>Factors in R. More dplyr. Data cleaning (recoding/renaming variables; missing data).</strong>"

# Links (optional).
url_pdf: ""
url_slides: "/slides/dplyr-more-and-cleaning/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Overview

* Define and use factors in R
* Review the fundamental `dplyr` "verbs" for data manipulation (see Lecture 3) and learn new ones
* Data cleaning: recoding and renaming variables; difference between syntactic vs. non-syntactic variable names
* Data cleaning: missing data


## Readings

Required:
* Review ["Chapter 16 Factors"](https://r4ds.hadley.nz/factors) from "R for Data Science" 2nd Edition. 
* Review ["Chapter 3 Data transformation"](https://r4ds.hadley.nz/data-transform) from "R for Data Science" 2nd Edition. This is the same chapter from the `dplyr` lecture (lecture 3), you might want to take a look again.

Optional/Skim:
* ["Chapter 18 Missing values"](https://r4ds.hadley.nz/missing-values.html) from "R for Data Science" 2nd Edition. Not immediately relevant, but offers several tips that could be beneficial for your future work.


## Class materials

In-class materials (exercises and code) will be posted here shortly before class.

<!--
Run the code below in your console to download today’s materials: `usethis::use_course("css-materials/dplyr-more-and-cleaning")`
-->