---
title: "Data transformation: more dplyr & relational data"
date: 2023-10-18T12:25:00-05:00
publishDate: 2019-04-17T12:25:00-05:00
draft: false

aliases: ["/cm006.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
#time_end: 2022-09-12T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Topics: review and expand your knowledge of dplyr for data transformation; relational data with dplyr."
# Note: might need to revise the summary if I drop factors from here


# Location of event.
location: ""

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/data-wrangling-relational-data-and-factors/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Dig deeper into `dplry` for data transformation
* Review of factors
* Introduce the use of `dplry` for relational data (e.g., linking and merging related tables)


## Before class

Readings
* Read Chapter 13 "Relational Data" in [R for Data Science](http://r4ds.had.co.nz/). Do not complete exercises 13.4.6.2-3 -- we will be completing these as in-class exercises
* Review Chapter 15 "Factors" in [R for Data Science](http://r4ds.had.co.nz/)

Mix
* Complete the in-class exercises from last lecture on tidy data; solutions will be pushed before class
* Fill out [this 2-min survey](https://docs.google.com/forms/d/e/1FAIpQLSdymbNtgrQFHgMzqPjxcpIjYqPSFvNBPohQnjtkr4GvFjRFBg/viewform) about the course 
* Questions about your HW1 feedback? book OH with Sabrina or catch her after class (if so, email her first)


## Class materials

* Run the code below in your console to download today’s materials: `usethis::use_course("css-materials/data-wrangling-relational-data-and-factors")`


<!--
* [Relational data: a quick review](/notes/relational-data/)
* [Practice using relational data](/notes/relational-data-exercise/)
* [Practice transforming and visualizing factors](/notes/factors-exercise/)
* [Complete the wrangling and visualizing data homework](/homework/wrangle-data/)
-->