---
title: "Exploratory data analysis"
date: 2022-10-11T12:25:00-05:00
publishDate: 2019-04-10T12:25:00-05:00
draft: false

aliases: ["/cm004.html"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
#time_end: 2022-08-31T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Define exploratory data analysis, practice exploring data with visualizations, and familiarize with factors."

# Location of event.
location: ""

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/exploratory-data-analysis/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Define Exploratory Data Analysis (EDA) and types of pattern exploration
* Demonstrate types of graphs useful for EDA and precautions when interpreting them
* Define factors
* Practice exploring data


## Before class

* Read Chapter 7 “Exploratory Data Analysis” and Chapter 15 "Factors" from [R for Data Science](http://r4ds.had.co.nz/)

## Class materials

* [Exploratory data analysis](/notes/exploratory-data-analysis/)
* [Practice exploring college education data](/notes/exploratory-data-analysis-practice/)

<!--
* Copied from the lecture on data wrangling, notes on factors: [Practice transforming and visualizing factors](/notes/factors-exercise/)
-->

## Additional resources

* Antony Unwin [Graphical Data Analysis with R](https://catalog.lib.uchicago.edu/vufind/Record/11609643#). It covers a range of graphical methods for data exploration and analysis; draws on packages beyond `ggplot2` for statistical graphics.
* Cheat Sheet [Data visualization with ggplot2](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf)

## What you need to do after class

* Work on homework 2
* Review today’s lecture materials, and prepare for next class