---
title: "Git/GitHub and R Markdown"
date: 2023-10-02T12:25:00-05:00
publishDate: 2019-05-01T12:25:00-05:00
draft: false

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
#time_end: 2022-10-17T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Review R basics, familiarize with R Markdown, and practice implementing Git/GitHub workflow."

# Location of event.
#location: "Kimball Hall B11"

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
#url_slides: "/slides/reproducible-examples-and-git/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Overview 

* Distinguish between R scripts (`.R`), Markdown documents (`.md`), and R Markdown documents (`.Rmd`)
* Identify the major components of R Markdown
* Familiarize with Git and GitHub
* Create repositories
* Make commits and synchronize repositories from RStudio


## Before class

* Review [Lecture 1](https://computing-soc-sci.netlify.app/syllabus/introduction-to-computing-for-the-social-sciences/) especially:
  * the intro to R code under "Class materials"
  * make sure your [Setup](https://computing-soc-sci.netlify.app/setup/) works as expected by completing [Using Git within R Studio](/setup/git/git-with-rstudio) 
* You should have received an invitation to join a GitHub organization, please accept it (we need your GitHub username to do so, see lecture 1)
* Readings:
  * Chapter 27 "R Markdown" and Chapter 29 "R Markdown formats" in [R for Data Science](https://r4ds.had.co.nz/r-markdown.html)
  * Chapter 1 "Why Git? Why GitHub?" in [Happy Git and GitHub for the useR](https://happygitwithr.com/big-picture)
  * "What are Git & GitHub?" under [FAQ](https://computing-soc-sci.netlify.app/faq/)


## Class materials

TBA
<!--
* Access RStudio Workbench [here](https://macss-r.uchicago.edu/s/57ea13c286bd33c286bd3/auth-sign-in?appUri=%2Fworkspaces%2F)
* Run the code below in your console to download today’s materials: `usethis::use_course("css-materials/intro-r")`[^local]
-->

## Additional resources

Consult these resources for further information about R Markdown, it is likely they provide the answer to what you need:
* [R Markdown the definitive Guide](https://bookdown.org/yihui/rmarkdown/)
* [R Markdown cheat sheet](https://posit.co/resources/cheatsheets/?_page=2/)
* [Markdown and R Markdown](https://pjbartlein.github.io/REarthSysSci/markdown.html) by Pat Bartlein
* [R Markdown from R Studio](https://rmarkdown.rstudio.com/lesson-1.html) official documentation